### ISSUE TITLE
Sunsa API batteryPercentage errors (None has no element 0)

### ISSUE THREAD

**Issue by GaryOkie** [r01k/ha_sunsa#1]
Just reporting errors with the API attempting to retrieve the battery percentage.   It's not serious since the actual percentage in HA is valid and matches the mobile app.  No other sensors have encountered errors like this.   Maybe just add a bit of additional error checking on unexpected results and move on.

```
2024-05-03 11:10:09.372 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sunsa which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-05-03 11:10:10.845 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.162 seconds (success: True)
2024-05-03 11:10:12.030 DEBUG (MainThread) [custom_components.sunsa] Instantiated cover: Sunsa Wand 3125
2024-05-03 11:10:12.040 DEBUG (MainThread) [custom_components.sunsa] Registered cover services
2024-05-03 11:10:12.153 DEBUG (MainThread) [custom_components.sunsa] Registered 4 sensors
 
2024-05-03 11:10:17.126 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ state_attr('sensor.api_sunsa_main', 'devices')[0]['batteryPercentage'] }}) renders=2>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 586, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2545, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 303, in getitem
return obj[argument]
~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: None has no element 0
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 712, in async_render_to_info
render_info._result = self.async_render(
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 588, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: None has no element 0

2024-05-03 11:10:17.129 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 0') while processing template 'Template<template=({{ state_attr('sensor.api_sunsa_main', 'devices')[0]['batteryPercentage'] }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.office_blinds_battery_level'
2024-05-03 11:10:18.062 ERROR (SyncWorker_5) [homeassistant] Error doing job: Unclosed connection

2024-05-03 11:10:32.422 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.185 seconds (success: True)
2024-05-03 11:10:52.403 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.167 seconds (success: True)
2024-05-03 11:11:12.408 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.172 seconds (success: True)
2024-05-03 11:11:32.416 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.179 seconds (success: True)
2024-05-03 11:11:52.445 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.208 seconds (success: True)
2024-05-03 11:12:12.408 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.172 seconds (success: True)
2024-05-03 11:12:32.399 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.163 seconds (success: True)
2024-05-03 11:12:52.410 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.174 seconds (success: True)
2024-05-03 11:13:12.462 DEBUG (MainThread) [custom_components.sunsa] Finished fetching sunsa data in 0.226 seconds (success: True
```)

![Screenshot](https://github.com/r01k/ha_sunsa/assets/37629938/350e9bc6-dc10-4654-b682-8bdbf3f9ec09)

**Comment by r01k** [comment]
Hello @GaryOkie.

Looks like the attempt to index the first element with `state_attr('sensor.api_sunsa_main', 'devices')[0]` fails because that `state_attr` call returns `None`.

```
2024-05-03 11:10:17.126 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ state_attr('sensor.api_sunsa_main', 'devices')[0]['batteryPercentage'] }}) renders=2>
Traceback (most recent call last):
...
jinja2.exceptions.UndefinedError: None has no element 0
```

Since the Sunsa integration does not present the battery level as device attribute, can you confirm that you have not integrated that wand using REST perhaps?

`state_attr('sensor.api_sunsa_main', 'devices')[0]['batteryPercentage']` gets the battery level for `sensor.office_blinds_battery_level` by indexing the devices array first. However, this integration retrieves that information by directly indexing the specific dictionary containing the device data:

https://github.com/r01k/ha_sunsa/blob/c42c8a269dcde7dfddd7c090536e12f385ff1b5c/custom_components/sunsa/sensor.py#L108C5-L112C64

```
  @callback
  def _handle_coordinator_update(self) -> None:
      """Handle updated data from the coordinator."""
      if self.device is not None:
          data = self.device.get(self.entity_description.key)
```

**Comment by GaryOkie** [comment]
Oops!  You’re exactly right.    I had removed all the original REST and COVER code from the config, but  overlooked the legacy battery level sensor that used the rest api.

My apologies!

```
      office_blinds_battery_level:
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[0]['batteryPercentage'] }}"
        unit_of_measurement: '%'
